### PR TITLE
Created events for when a user joins or leaves a voice channel

### PR DESCRIPTION
**Pull request by AdenFlorian**
`UserJoinedVoiceChannel` and `UserLeftVoiceChannel`

### CODE REVIEW

**Comment by AdenFlorian** [comment]
Why only one?

**Comment by RogueException** [comment]
I'm unsure if this is needed, we already have an event for general user updates. If we add this, where do we draw the line? What about username changes, game changes, etc.

I merged everything into a single event because I thought it made it easier having all user changes in one place.

**Comment by AdenFlorian** [comment]
@RogueException Ok, cool, that's kind of what I was wondering I guess (where y'all wanted to draw the line).

**Comment by RogueException** [comment]
Closing this, unless someone has a good argument of why it should be added

**Pull request closed without merging**
