### PR TITLE
Add support for changing Nicknames!

### PR DESCRIPTION
**Pull request by Lirusaito**
```cs
User.Edit(nickname: "foo");
```

### CODE REVIEW

**Comment by RogueException** [comment]
Does this work for yourself? The client hits a members/@me/nick endpoint instead.

**Comment by Lirusaito** [comment]
Works for me, I have a command
```cs

            group.CreateCommand("nickname")
                .MinPermissions(10)
                .Parameter("nick", Commands.ParameterType.Unparsed)
                .Do(e => e.User.Edit(nickname: string.Join(" ", e.Args)));
```
And here's a log from its use:
```
[12:14 AM] Liru: ~nickname woof
[12:14 AM] BOTDog: Liru: Error: Command Error: The server responded with error 403 (Forbidden)
[12:15 AM] Liru: ~nickname woof
[12:17 AM] woof: ~nickname
[12:17 AM] Liru: Yay
```
(The first time it didn't work because of the new role hierarchy mess.

**Comment by Lirusaito** [comment]
OH! You mean editing the bot's own nickname? I hadn't tried that, gimme a moment.

**Comment by Lirusaito** [comment]
Ah, you are right!

**Comment by Lirusaito** [comment]
Any ideas for how we can have an Edit with nickname with other params set too that can work on self?

**Comment by Lirusaito** [comment]
Alright, tell me what you think of this... not sure I like it myself.

**Comment by RogueException** [comment]
Looks good. I also cleaned up User.cs a bit to match 1.0's logic.

Thanks for the PR, Liru~

**Pull request merged**
