### PR TITLE
Add support for attachments on interaction response type 7

### PR DESCRIPTION
**Pull request by d4n3436**
This PR adds support for modifying attachments on interaction response type 7 (`SocketMessageComponent.UpdateAsync`).

### CODE REVIEW

**Comment by csmir** [comment]
Could you also cover this for rest message components?

**Comment by d4n3436** [comment]
> Could you also cover this for rest message components?

That would require a rewrite of REST interactions due to the way they are designed.

**Comment by csmir** [comment]
Could you clarify? The Update() method does the exact same as UpdateAsync() except that it does not directly hook into the response callback like socket interactions. There is no need to make any edits other than the action itself

**Comment by d4n3436** [comment]
> The Update() method does the exact same as UpdateAsync() except that it does not directly hook into the response callback like socket interactions.

What does that mean? Update() returns a JSON string that is used to respond to the HTTP request and it can't support files because `UploadInteractionFileParams` is not meant to be serialized to a JSON string (unlike `InteractionResponse`).

**Review by quinchs — APPROVED** [review]

**Pull request merged**
