### PR TITLE
Expose IsNsfw prop directly in ITextChannel

### PR DESCRIPTION
**Pull request by ghost**
See [this](https://github.com/RogueException/Discord.Net/issues/772) issue.

### CODE REVIEW

**Comment by Joe4evr** [comment]
#771?

**Comment by ghost** [comment]
Anyway, why did CI fail?

**Comment by AntiTcb** [comment]
The XML malformations are just warnings, but this was an error:
```
Discord.Net.Core -> C:\Projects\Discord.Net\src\Discord.Net.Core\bin\Release\netstandard1.1\Discord.Net.Core.dll
Entities\Channels\RestTextChannel.cs(12,75): error CS0535: 'RestTextChannel' does not implement interface member 'ITextChannel.IsNsfw'
```

**Comment by ghost** [comment]
Yep, just saw that.

**Pull request closed without merging**
