### PR TITLE
Get docs working on latest docfx version.

### PR DESCRIPTION
**Pull request by AnalogFeelings**
### Description
This PR aims to get the documentation to build and function on the latest DocFX versions.

It also modernizes the overall look of the page.

TODO:
- [x] Get the docs functional again.
- [x] Make derived tree readable.
- [x] Fix broken links.

### Changes
- Fixes modern DocFX compatibility.
- Modernizes appearance.

### Related Issues
None.

### CODE REVIEW

**Comment by AnalogFeelings** [comment]
@Still34 hey, is it too much to ask if you try to get LastModified and DescriptionGenerator working on latest docfx? I have no experience with DocFX postprocessors and the documentation is a bit shady.

**Comment by Still34** [comment]
Uhh, I can try later tonight maybe - I have a vacation coming up soon but I'll try.

**Comment by AnalogFeelings** [comment]
I got them to build but it couldnt find the libgit2sharp native deps, and if I copied them over manually they didnt apply the commit info at all even though it says it did. I have no idea whats going on with them

**Comment by Misha-133** [comment]
image

**Comment by Misha-133** [comment]
image
Also
"In this article" title is quite hard to read in light theme

**Comment by AnalogFeelings** [comment]
> image

Are you sure it built correctly? DocFX will still serve the site if the library fails to build.

**Comment by AnalogFeelings** [comment]
> image Also "In this article" title is quite hard to read in light theme

Will look into it, should be a simple fix

**Comment by Misha-133** [comment]
> Are you sure it built correctly? DocFX will still serve the site if the library fails to build.

image

I'm using the latest docfx version btw

**Comment by Misha-133** [comment]
image
found more clues

Pretty sure it's not something related to my setup, as I'm re-cloning your repo every build

**Comment by AnalogFeelings** [comment]
Rebased the PR.

**Comment by AnalogFeelings** [comment]
> image found more clues
> 
> Pretty sure it's not something related to my setup, as I'm re-cloning your repo every build

Erased my local copy from my disk and recloned it, still can build it fine. Maybe my .NET version is to blame?

image

**Comment by AnalogFeelings** [comment]
> > image found more clues
> > Pretty sure it's not something related to my setup, as I'm re-cloning your repo every build
> 
> Erased my local copy from my disk and recloned it, still can build it fine. Maybe my .NET version is to blame?
> 
> image

I made sure I was building it with .NET 7.0, then I checked docfx version. I was in 2.70, but I found out 2.71 released a while ago. Gonna try to see if I can reproduce.

**Comment by AnalogFeelings** [comment]
Rebased to latest dev.

**Review by Misha-133 — APPROVED** [review]

**Pull request merged**
