### PR TITLE
Added Extension Methods for WebSocket

### LINKED ISSUE #146: Add extension methods specific to the type of connection
While not required, these methods should really help out users by not requiring async for all actions.

We should also look into moving GetCachedMessage from IMessageChannel to an extension method for WS.

### PR DESCRIPTION
**Pull request by 420foxbot**
Resolves #146.

Adds extension methods to `IGuildChannel` and `IChannel` types for WebSocket users.

### CODE REVIEW

**Comment by khionu** [comment]
LGTM

**Comment by RogueException** [comment]
What about adding a sync way to get the existing collections?

Channel.GetUsers instead of Channel.GetUsersAsync

**Comment by RogueException** [comment]
ICollection~

**Comment by RogueException** [comment]
LGTM

**Pull request merged**
