### PR TITLE
Fix parsing double quoted parameters (#262)

### PR DESCRIPTION
**Pull request by AdamPatenaude**
This fixes (or adds support for, i'm not really sure, looking at the code, that it was originally intended) parsing for parameters in double quotes as mentioned in #262.
This doesn't include the quotes with the parameter and also doesn't work with single quotes but both could be fixed easily.

### CODE REVIEW

**Comment by khionu** [comment]
Umm..... #262 is referring to the Dev Branch..... this functionality already works in 0.9 (Master Branch)

**Comment by AdamPatenaude** [comment]
Well then, I tried. 

But from what I've seen, the algorithm in the Master branch simply ignores quotes and doesn't actually consider everything in them as a parameter.
I've done my own testing, but not in the "official" tests.

**Comment by khionu** [comment]
It's been a while since I used 0.9, but I recall being able to use these with no issue. Given there is no open issue for this for 0.9, I don't think this should be accepted. We don't know it's broken, so let's leave it as is

**Comment by RogueException** [comment]
I'm avoiding touching the 0.9 branch unless absolutely necessary, and I don't remember this ever being an issue o.O.

**Comment by khionu** [comment]
Agreed. This wasn't an issue for 0.9. Cited Issue is for 1.0

**Pull request closed without merging**
