### PR TITLE
Add characters commonly used in links to Sanitize

### PR DESCRIPTION
**Pull request by FiniteReality**
In light of a recent attack on The Coding Den, I felt it was necessary to set a precedent and add characters commonly used in links to our markdown sanitizer. This way, bots using `Format.Sanitize` as it was intended will be able to not have link text turn into clickable hyperlinks.

This will be most helpful for bots who have join/leave messages, as this will prevent usernames with invite codes in their names from creating the invite modal. (e.g. `discord.gg/code#1234` will be escaped to `discord\.gg\/code#1234`.) This should help alleviate part of the underlying issue of Discord allowing invite links in usernames/nicknames.

### CODE REVIEW

**Comment by petrspelos** [comment]
I think this is a great improvement, thank you for that! :heart: @FiniteReality

**Comment by Hellman6669** [comment]
Best code i've seen all day! ~

**Comment by AraHaan** [comment]
Is this PR abandoned?

**Comment by AraHaan** [comment]
@FiniteReality can this be updated?

**Pull request merged**
