### PR TITLE
Fix: Not using the new domain name.

### PR DESCRIPTION
**Pull request by BrammyS**
### Summary
---
Changed the domain name from discordapp.com to discord.com
This change is needed because Discord is planning to require the new domain.

### Changes
---
- Changed the domain name in the code.
- Changed the domain name in the documentation.

### References
---
https://discord.com/developers/docs/reference

### CODE REVIEW

**Comment by Nicolas-Ding** [comment]
Thanks :) I was looking for this

**Comment by tornapi** [comment]
You should include the referenced subdomains in this PR as well.
Only cdn.discordapp.com will remain the same. 
Subdomains such as canary, support, and ptb all resolve using the new discord.com domain.

**Review by ArcticLampyrid — APPROVED** [review]

**Comment by zoeleu** [comment]
Why isn't this pulled yet?

**Comment by BrammyS** [comment]
> Why isn't this pulled yet?

I don't know.

**Review by ArcticLampyrid — APPROVED** [review]

**Comment by FiniteReality** [comment]
"No need" my ass.

**Comment by Pikeman** [comment]
👍 

When I last heard from Discord, they were planning to drop the old domain on November 7. Are you planning to create a new release of Discord.Net before then?

image

**Comment by Joe4evr** [comment]
@Pikeman This PR is merged, so it's already out. Get your updates from the MyGet feed.

**Comment by liny-fox** [comment]
Is there any update on this? MyGet isn't an option for some as its not a stable release.

**Pull request merged**
