### PR TITLE
Improved null check on getting AssemblyInfo

### PR DESCRIPTION
**Pull request by Carbonitex**
Fixes an exception when you have an AssemblyInfo but are missing InformationalVersion.

### CODE REVIEW

**Comment by khionu** [comment]
>< Should have made two PRs....

**Comment by RogueException** [comment]
Duplicate

**Comment by khionu** [comment]
Not a duplicate >< This one was badly named, it's the sharding one, the other is both issues in one.

**Comment by RogueException** [comment]
If it contains both, that's close enough to a duplicate lol

**Pull request closed without merging**
