### PR TITLE
Added method to flatten paged content into one async collection

### PR DESCRIPTION
**Pull request by ObsidianMinor**
Now you can use LINQ with your async collections. Have fun.

### CODE REVIEW

**Comment by ObsidianMinor** [comment]
This could wait until C# 8 so I can replace the PagedCollectionEnumerator<T> with just a yield return

**Comment by Still34** [comment]
Wouldn't the release take another year or so?

**Comment by ObsidianMinor** [comment]
Discord.Net 2.x could also take another year. So it depends on if both C# 8 and the next major version are released near each other I guess.

**Comment by Still34** [comment]
I don't think 2.0 will take that long to release, as 2.0 includes some breaking changes that need to be pushed ASAP. 3.0 would make more sense for integrating C#8 changes.

**Pull request merged**
