### PR TITLE
Add Localization Support to Interaction Service

### PR DESCRIPTION
**Pull request by Cenngo**
This PR adds Application Command localization to Core, Rest and WebSocket projects. Introduces a `ILocalizationManger` interface and default Localization Managers for Json and ResX in preperation for the Slash Commands localization feature release.

Two LocalizationManagers ship with this update, JsonLocalizationManager and ResxLocalizationManager.

JsonLocaliationManager uses a nested data structure similar to Discord's Application Commands schema. You can get the Json schema [here](https://gist.github.com/Cenngo/d46a881de24823302f66c3c7e2f7b254). LocalizationManager accepts a base path and a base file name and automatically discovers every resource file ( `\basePath\fileName.locale.json`  ). 

```json
{
    "command_1":{
        "name": "localized_name",
        "description": "localized_description",
        "parameter_1":{
            "name": "localized_name",
            "description": "localized_description"
        }
    },
    "group_1":{
        "name": "localized_name",
        "description": "localized_description",
        "command_1":{
            "name": "localized_name",
             "description": "localized_description",
             "parameter_1":{
                 "name": "localized_name",
                  "description": "localized_description"
            },
            "parameter_2":{
                 "name": "localized_name",
                  "description": "localized_description"
            }
        }
    }
}
```

ResxLocalizationManager uses the [naming scheme](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-6.0#resource-file-naming) used by ASP.NET ( `group1\command1\parameter2.fr-FR.resx` or  `group1.command1.parameter2.fr-FR.resx` ). Every resx file must have two fields: name and description. Individual .resx files can be defined for every group/command/parameter. Space characters within Context command names are tokenized with tilde character.

Interaction Service can be easily configured to use any `ILocalizationManager` implementation by setting the LocalizationManager field of InteractionServiceConfig.

## TODO
- [x] Add per-request header support to rest client(#2261)
- [x] Add localization support to parameter choices
- [ ] Add locale parameter to Get*ApplicationCommandsAsync methods for fetching localized name and description strings

## Breaking Changes
```diff
- A new requestHeaders parameter is added to every Send* method of IRestClient.
```

### CODE REVIEW

**Comment by MoonieGZ** [comment]
This is EXACTLY what I need, thank you for working on it ♥

**Comment by Cenngo** [comment]
> This is EXACTLY what I need, thank you for working on it ♥

Thanks but you should be thanking Discord, im just adding API support to the library

**Comment by MrCakeSlayer** [comment]
@Cenngo any update/progress on this?

**Comment by Cenngo** [comment]
Everything is ready except i need to make a minor modification to GetApplicationCommands methods but #2261 needs to be merged to a branch other than 4.0 before i can do that

**Comment by Cenngo** [comment]
Moved to #2395.

**Pull request merged**
