### PR TITLE
[ci skip] Fixing GatewayEncoding comment

### PR DESCRIPTION
**Pull request by moiph**
Const, not a property

### CODE REVIEW

**Comment by Niewiarowski** [comment]
Thanks for your contribution. Can't wait for this to be merged. I can't believe no one noticed this before. I'm fairly certain that this will provide a huge performance boost. This is just what this library needed. I cannot express how thankful I am to you. I hope to see more from you! Keep it up.

**Comment by jacksonrakena** [comment]
Documentation changes should have a `[ci skip]` label (See [this docs PR](https://github.com/discord-net/Discord.Net/commit/15b2a36790ceaab453d001d939d039860592dd0d))

**Comment by GreemDev** [comment]
I'd recommend changing that from `returns` to `represents` or something similar; as a const is not a method.

**Comment by moiph** [comment]
> I'd recommend changing that from `returns` to `represents` or something similar; as a const is not a method.

I'd agree but I'm just following language already set by other `const` related comments

**Comment by GreemDev** [comment]
> I'd agree but I'm just following language already set by other `const` related comments

change all the other ones then lol

**Pull request merged**
