### PR TITLE
Fix UpdateAsync Remove Attachment Bug

### PR DESCRIPTION
**Pull request by supitsmike**
### Description
This PR adds the ability to remove attachments for a `IModalInteraction` when calling `UpdateAsync`.

### Changes
- Add `Attachments` object to `InteractionCallbackData`.
- Update `UpdateAsync` to add `Attachments` object to both `RestModal` and `SocketModal`.

### Related Issues
- Similar to #2742

### CODE REVIEW

**Comment by DeclanFrampton** [comment]
Not the best way, however, this has already been pushed awaiting review and merge #2753

**Comment by supitsmike** [comment]
> Not the best way, however, this has already been pushed awaiting review and merge #2753

Your PR #2753 and my PR #2766 are fixing a similar issue it 2 totally different places.
I pulled your PR and tested it and it still kept the image after setting `Attachments` to `null`.

**Review by SupItsTom — APPROVED** [review]

**Comment by DeclanFrampton** [comment]
Issue resolves another issue similar to #2753 and #2236. Tested changes and approve the changes within this PR. 

Can we get high priority on this for next release @Misha-133

**Review by DeclanFrampton — APPROVED** [review]

**Review by Misha-133 — CHANGES_REQUESTED** [review]
Adding a `FileAttachment` property to json model would not allow sending new attachments.
Same approach as in [SocketMessageComponent](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.WebSocket/Entities/Interaction/MessageComponents/SocketMessageComponent.cs#L268-L304) should be used instead.

Additionally, `RestMessageComponent.Update` should also be updated to allow setting `Attachments`

**Comment by supitsmike** [comment]
> Adding a `FileAttachment` property to json model would not allow sending new attachments. Same approach as in [SocketMessageComponent](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.WebSocket/Entities/Interaction/MessageComponents/SocketMessageComponent.cs#L268-L304) should be used instead.
> 
> Additionally, `RestMessageComponent.Update` should also be updated to allow setting `Attachments`

@Misha-133 Updated those functions and `RestMessageComponent.Update`

**Review by Misha-133 — APPROVED** [review]

**Pull request merged**
