### PR TITLE
Allow setting IgnoreExtraArgs on an individual basis

### PR DESCRIPTION
**Pull request by Joe4evr**
Someone in DAPI requested the ability to override the config setting on an individual command basis.

Also removes some stray comments and unused usings.

### CODE REVIEW

**Comment by Joe4evr** [comment]
I don't like that approach because it'd make it impossible to set the value on a Module-wide basis.

I'd rather push for the `RunMode` setting to be promoted to its own attribute like this instead.

**Comment by pengowray** [comment]
Was this really never merged?

**Comment by Still34** [comment]
Pretty sure it is merged?

**Comment by pengowray** [comment]
Apologies. You are correct.

For easy/future reference:

This works:
```C#
[Command("hello", ignoreExtraArgs: true)]
```

This **does not** work:
```C#
[Command("hello", IgnoreExtraArgs = true)]
```

**Pull request merged**
