### PR TITLE
Added bot authorization headers

### PR DESCRIPTION
**Pull request by Googie2149**
Basically grabbed this from 1.0, thank you Rand for all the help

### CODE REVIEW

**Comment by RogueException** [comment]
Should get rid of Bearer, 0.9 does not support it in any way

**Comment by RogueException** [comment]
Was this tested with bot tokens?
I feel like the Gateway might complain o.O

**Comment by Googie2149** [comment]
Been working fine all day for a bot account

**Comment by RogueException** [comment]
Hmm okay, sounds good them

**Pull request merged**
