### PR TITLE
Patch; Webhook regex doesn't respect case-sensitive url's

### LINKED ISSUE #2074: Couldn't parse Discord Canary webhook URLs
Relevant stack trace :
```
System.ArgumentException: The given webhook Url was not in a valid format. The webhook Id could not be parsed. (Parameter 'webhookUrl')
   at Discord.Webhook.DiscordWebhookClient.ParseWebhookUrl(String webhookUrl, UInt64& webhookId, String& webhookToken)
   at Discord.Webhook.DiscordWebhookClient..ctor(String webhookUrl, DiscordRestConfig config)
```
The webhook URL in question was `https://canary.discord.com/api/webhooks/937967020320899092/BWKbVhNqu5shH9t96qWQKlzYisoHmM7PIMv88-IokTdR-lwHX7fNeWKk_Y2VBtSJpD2b`
image
(I made sure to invalidate the webhook URL for security purposes, it's fine to pass this around).

### PR DESCRIPTION
**Pull request by csmir**
Fixes #2074.

### CODE REVIEW

**Review by MichailiK — CHANGES_REQUESTED** [review]
Because `RegexOptions.IgnoreCase` is specified, this does not change anything.

**Comment by csmir** [comment]
Ah, I probably missed that. It seems to match the string with or without canary in Regex101, so other causes do not make sense to me?

**Comment by csmir** [comment]
image
As implied here, the webhook ID seems to match group 2 with index 3. This seems executed quite well. The canary case is entirely ignored with or without this present.

image

image

Error thrown in issue 2074 implies that the ulong is mismatched. Here it implies that that would be impossible.

**Comment by csmir** [comment]
Upon testing now, it appears that ptb & canary work fine regularly. Quite a waste of effort to check internally before testing.

**Pull request closed without merging**
