### PR TITLE
[Fix] Make `ref` parameter of `message.HasCharPrefix`, `message.HasStringPrefix`, `message.HasCharPrefix` to be `out`

### PR DESCRIPTION
**Pull request by vladflotsky**
I think it`s better in terms of logic.

### CODE REVIEW

**Comment by Cenngo** [comment]
What makes you think that replacing `ref` with `out` is better? argPos might already have an assigned value when control enters the method. `out` is only used when a parameter is definitely going to be reassigned or initialized in the method which isnt the case here.

**Comment by vladflotsky** [comment]
At a minimum, these methods don't need a value of dev's argPos.

**Comment by KubaZ2** [comment]
> What makes you think that replacing `ref` with `out` is better? argPos might already have an assigned value when control enters the method. `out` is only used when a parameter is definitely going to be reassigned or initialized in the method which isnt the case here.

What about `int.TryParse`? The second parameter is `out`, not `ref`.

I was always wondering why there is `ref` in this methods, but I was thinking that there is a reason. But now, I am seeing that there is no reason to use `ref`.

**Review by csmir — COMMENTED** [review]
> This change is breaking and would need to be pushed to v4x.

ref is used in cases where the user has already done a check on a previous segment and passes a different arg position into the method. I do not approve of this change myself.

**Pull request closed without merging**
