### PR TITLE
Added UpdateAsync to SocketModal

### PR DESCRIPTION
**Pull request by serkanyazicioglu**
At the moment Modals cannot update initial interacted message. I added a UpdateAsync method similar to message components.

### CODE REVIEW

**Comment by Almighty-Shogun** [comment]
Modals can also do this with:
```cs
await DeferAsync();
await ModifyOriginalResponse(x => {});
```

**Comment by serkanyazicioglu** [comment]
Yeah checked a lot of combinations but missed this one I guess. Tried it now and it's working.

Not sure about making this non-standard. If this method will not be added at least your recommendation should be documented, it can be really helpful for others.

**Comment by quinchs** [comment]
iirc modals were non-deferrable and non-updatable? Will check with a few people first.

**Comment by quinchs** [comment]
apparently this is a feature so it lgtm

**Review by quinchs — APPROVED** [review]

**Pull request merged**
