### PR TITLE
Resolve #384: Add upward reference for submodules

### LINKED ISSUE #384: Upward reference for submodules
Right now ModuleInfo currently has a `Submodules` property that provides access to modules nested within other modules, but there is no way for a obtain the parent module from the submodule. This is an issue if trying to obtain the full hierarchy from a given CommandInfo. Additionally, with `CommandService.Modules` enumerating all modules, whether they're a top level module or not, there is no way to tell if a module is a submodule. 

A solution that I propose:
 * Provide a `Parent` property on ModuleInfo, referring to the parent module, left null for top-level modules.
* Limit `CommandService.Modules` to only top level modules.

### PR DESCRIPTION
**Pull request by james7132**
This currently has the proposed solution mentioned in #384.

### CODE REVIEW

**Comment by RogueException** [comment]
@FiniteReality you've been championing commands lately, mind taking a look at this?

**Comment by FiniteReality** [comment]
Oh hey, I forgot about email replies. I'm fine with these changes; though I
think it would be nice if there were still a way to access all modules as
we do have the data internally. Maybe we should split it into
`CommandService.AllModules` and `CommandService.TopLevelModules`?

**Comment by james7132** [comment]
It may be better and more succinct to revert CommandService.Modules to what it was before, and let devs apply the filter as needed.

**Comment by FiniteReality** [comment]
Yeah, that would probably be the best approach. Other than that, LGTM

**Comment by james7132** [comment]
Done. PTAL.

**Comment by FiniteReality** [comment]
Nothing else needs to be done here, right? This looks ready to merge @RogueException

**Pull request merged**
