### PR TITLE
Fixing localizations

### PR DESCRIPTION
**Pull request by Hampo**
* Fixed typo in `SlashCommandOptionBuilder.WithDescriptionLocalizations`
* Fixed typo in `SlashCommandOptionBuilder.AddNameLocalization`
* Changed `Build` method of both `SlashCommandBuilder` and `SlashCommandOptionBuilder` to not set the `NameLocalizations` and `DescriptionLocalizations` if null in the builder. Was causing an error in the setter.

### CODE REVIEW

**Comment by Cenngo** [comment]
duplicate of #2453?

**Comment by Hampo** [comment]
> duplicate of #2453?

Looks like, but with an additional fix that isn't in that one: https://github.com/discord-net/Discord.Net/pull/2457/files#diff-8c81295400c8d6282cd4cf4396b20a47631dac9129cbc1f3496ec1546ea9f3c8R945

**Comment by Cenngo** [comment]
> Looks like, but with an additional fix that isn't in that one: https://github.com/discord-net/Discord.Net/pull/2457/files#diff-8c81295400c8d6282cd4cf4396b20a47631dac9129cbc1f3496ec1546ea9f3c8R945

to me it looks like SlashCommandBuilder#L936 is the only line thats needs to be updated after the merge of #2453. Everything else seems to be taken care of in that PR. Can you update your PR accordingly?

**Comment by Hampo** [comment]
> > Looks like, but with an additional fix that isn't in that one: https://github.com/discord-net/Discord.Net/pull/2457/files#diff-8c81295400c8d6282cd4cf4396b20a47631dac9129cbc1f3496ec1546ea9f3c8R945
> 
> to me it looks like SlashCommandBuilder#L936 is the only line thats needs to be updated after the merge of #2453. Everything else seems to be taken care of in that PR. Can you update your PR accordingly?

Done

**Review by Cenngo — APPROVED** [review]

**Pull request merged**
