### PR TITLE
Update voice OP codes

### PR DESCRIPTION
**Pull request by Still34**

### CODE REVIEW

**Comment by MinnDevelopment** [comment]
Where are you using these?

**Comment by Still34** [comment]
Several people have complained about `Unknown Opcode: 8` in the past, figured the lib should have the updated list.

**Comment by MinnDevelopment** [comment]
Some of these codes only apply to v3 of the voice gateway so if you change them you should also make sure you use the correct version of that.

**Comment by Emzi0767** [comment]
This commit would actually break voice, unless you switcg VGW to v3, and implement the remaining logic for that.

**Comment by Still34** [comment]
I actually did not realize that we weren't using the latest Gateway for voice. My bad, although I might look into implementing them. For now, I will close the PR and examine this myself first.

**Pull request closed without merging**
