### PR TITLE
Added check to ignore bot commands.

### PR DESCRIPTION
**Pull request by Rithari**
Added the usual check to ignore bot commands in this sample CommandHandler as seen and approved in #1174.

### CODE REVIEW

**Review by Herdo — COMMENTED** [review]
In the sample, some additional comments would be great, explaining the conditions in the `if`-statement.

**Comment by Still34** [comment]
@Herdo that would fit more in line with the tutorial snippet of `Introduction to Command Service` instead of the `Post-execution Handling` snippet, which is what this PR changes.

**Comment by Rithari** [comment]
Hi, this being a more advanced snippet treating something different than the initial set up, I think that the suggested comments are redundant. 

Sincerely, 
Rithari

**Review by Herdo — APPROVED** [review]

**Comment by Still34** [comment]
With that being said, adding comments to the files mentioned would still be appreciated, as that was a valid suggestion - just on a different file.

**Comment by Rithari** [comment]
I'm pretty sure there were comments added on my behalf as well - should there be none I'll do a PR.

**Pull request merged**
