### PR TITLE
Added BulkMessageDelete Functionality

### PR DESCRIPTION
**Pull request by khionu**

### CODE REVIEW

**Comment by RogueException** [comment]
.cs files shouldn't be copied to both projects. Add them to the xproj ones and add a link in the csproj.
There should be zero code files in the csproj folders whatsoever apart from AssemblyInfo.cs.

**Comment by khionu** [comment]
O.o but I fixed that.... https://github.com/RogueException/Discord.Net/pull/73/commits/8bd02d437795cf7168a0004cb3cc2ceaca2002d1 was supposed to fix that, I could tell from the structure that that wouldn't be acceptable....

**Comment by khionu** [comment]
Then the third commit..... wtf VS....

**Comment by khionu** [comment]
Ok, I'm going to close this, and redo it a third time....

**Pull request closed without merging**
